### ISSUE TITLE
Travis-CI can not find Cortex module

### ISSUE THREAD

**Issue by joeljpoulin** [rdevon/cortex2.0#130]
Builds are failing running test, because it can not find the Cortex module. A solution needs to be found for Cortex to be installed inside Travis-CI environment. Tox integration can maybe resolve the bug.

**Comment by rdevon** [comment]
I think this can just be done by telling travis to install cortex (`pip install .`)

https://docs.travis-ci.com/user/languages/python/

Under the section marked "PyPy support".

**Comment by joeljpoulin** [comment]
PR #131 contains the fix.
