### ISSUE TITLE
Built-ins ModelPlugin needs obligatory comments documentation to be functional. 

### ISSUE THREAD

**Issue by joeljpoulin** [rdevon/cortex2.0#154]
The parser from parsing.py is looking for documentation of models (under the class name and routine method) obligatory or it will generate an error.

**Comment by rdevon** [comment]
Though you'll only see this bug if you're a developer. Models implemented a la demos don't have this issue.

**Comment by joeljpoulin** [comment]
@rdevon OK

**Comment by joeljpoulin** [comment]
Right. Is it an issue then?

**Comment by joeljpoulin** [comment]
Resolved in PR #159.
